#! /bin/sh

sxhkd &
exec nitrogen --restore &
exec compton &
.config/polybar/launch.sh

bspc monitor -d I II III IV V VI VII VIII IX X


#border colors
bspc config normal_border_color "#FBFBFB"
bspc config focused_border_color "#F8C6F1"


bspc config border_width         4
bspc config window_gap           16

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Firefox desktop='^1'
bspc rule -a qBittorrent desktop='^10' follow=off state=tiled
bspc rule -a discord desktop='^9'follow=off
bspc rule -a kitty
bspc rule -a vlc follow=on desktop='^4'
#bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
#bspc rule -a Screenkey manage=off

qbittorrent &
discord &
